Added -pthread to LDLIBS in Makefile. Testing on other computers revealed an undefined reference to pthread error. The main computer atINFLATE 3.0 was tested on compiled without error, but other computers require this flag in the final step of compilation.